### ISSUE TITLE
The robot hand is not showed correctly with Rviz

### ISSUE THREAD

**Issue by onioni0202** [MrLacquer/HRI-Hand-ROS#1]
I tried to follow "How to start?" and simulate the robot hand with Rviz, but the fingers were not displayed. Below are the logs after running roslaunch and the screenshot. Could you tell me how to fix that? Thanks in advance.
```
mech-user@****:~$ roslaunch hri_hand_control hri_hand_control.launch 
... logging to /home/mech-user/.ros/log/71aff85a-1980-11eb-a7f1-20791860f19e/roslaunch-KI0221-2645.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
Deprecated: xacro tag 'hj_hand' w/o 'xacro:' xml namespace prefix (will be forbidden in Noetic)
when processing file: /home/mech-user/catkin_ws/src/HRI-Hand-ROS/hri_hand_control/urdf/hj_hand_world.urdf.xacro
Use the following command to fix incorrect tag usage:
find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'

started roslaunch server http://KI0221:34891/

SUMMARY
========

PARAMETERS
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.9

NODES
  /
    robot_state_publisher (robot_state_publisher/state_publisher)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [2659]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 71aff85a-1980-11eb-a7f1-20791860f19e
process[rosout-1]: started with pid [2670]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [2677]
process[rviz-3]: started with pid [2678]
[ WARN] [1603932503.101690157]: The 'state_publisher' executable is deprecated. Please use 'robot_state_publisher' instead
```
![Screenshot from 2020-10-29 09-23-25](https://user-images.githubusercontent.com/49858062/97512941-26369200-19ce-11eb-9f44-6f0528715227.png)

**Comment by hj26-park** [comment]
Hi,

Can you try to `rosrun hri_hand_control hri_joint_state_pub.py` after the launch file?
If you run only the launch file, that screenshot is normal, cuz there is no joint_state topic publisher.

**Comment by onioni0202** [comment]
I tried it before connecting the robot, and I misunderstood the mesh data of fingers were not read correctly. Thanks.

**Comment by hj26-park** [comment]
I have tested on the new PC, it was successful.
In the `hri_joint_state_pub.py` has a serial connect line for connecting the robot hand.
So, maybe, if there is no serial adapter or something, the error is coming out.

If you wanna test this rviz package without the HRI hand, comment out all the code lines related to the serial class.

**Comment by onioni0202** [comment]
When I commented out them, it went well ! 
Thank you so much.
